// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TestData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_TESTDATA_H_
#define _FAST_DDS_GENERATED_TESTDATA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TESTDATA_SOURCE)
#define TESTDATA_DllAPI __declspec( dllexport )
#else
#define TESTDATA_DllAPI __declspec( dllimport )
#endif // TESTDATA_SOURCE
#else
#define TESTDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TESTDATA_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure SimpleInfo defined by the user in the IDL file.
 * @ingroup TestData
 */
class SimpleInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SimpleInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SimpleInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SimpleInfo that will be copied.
     */
    eProsima_user_DllExport SimpleInfo(
            const SimpleInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SimpleInfo that will be copied.
     */
    eProsima_user_DllExport SimpleInfo(
            SimpleInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SimpleInfo that will be copied.
     */
    eProsima_user_DllExport SimpleInfo& operator =(
            const SimpleInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SimpleInfo that will be copied.
     */
    eProsima_user_DllExport SimpleInfo& operator =(
            SimpleInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x SimpleInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SimpleInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SimpleInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SimpleInfo& x) const;

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            uint32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport uint32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport uint32_t& id();


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name();

private:

    uint32_t m_id{0};
    std::string m_name;

};

#endif // _FAST_DDS_GENERATED_TESTDATA_H_



